### ISSUE TITLE
IE Support

### ISSUE THREAD

**Issue by joaotocilo** [albert-gonzalez/easytimer.js#1]
I'm using the library on Internet Explorer, I'm having some problems. Does the Library support Internet Explorer?

**Comment by albert-gonzalez** [comment]
Hi!

You are right, there were a compatibility issue with Internet Explorer (they don't support Event object by default). I have included a polyfill which defines CustomEvent and now the library works in IE9 and newer versions. I can't make it work in older IEs because they doesn't have the addEventListener function, which is used in easytimer. Now you can download the 1.0.1 version with this fix.

If you need to make it work in older IEs you can use some library like this https://gist.github.com/jonathantneal/2415137, it should fix the problem. 

Regards!

**Comment by joaotocilo** [comment]
Hi!

Thank you a lot for the library update and add IE 9+ support, it was all I needed. I did library update and worked perfectly.

One more time, thank you!
Best Regards!
