### ISSUE TITLE
Error in guide

### ISSUE THREAD

**Issue by sengiv** [albert-gonzalez/easytimer.js#143]
Great repo, nice work!
But got little error in your user guide
`var timerInstance = new easytimer.Timer();`
should be
`var timer = new easytimer.Timer();`

`var timer = new Timer(/* default config */);`
should be
`var timer = new easytimer.Timer(/* default config */);`

i can make the pr if you want

**Comment by albert-gonzalez** [comment]
Hi!

Thank you! I am glad you like it.

I think the guide is correct, because:
- You can assign the new timer to a variable with any name. For example timer, timerInstance, clock...
- If you import the lib as a module (with import or require), you can use directly Timer instead of easytimer.Timer.

Best regards!
