### ISSUE TITLE
Events every 60 seconds

### ISSUE THREAD

**Issue by gtraxx** [albert-gonzalez/easytimer.js#47]
Hi, I want to create a counter that every 60 seconds run an event but I have to start the counter at the click of a button.
And if in events the result is false, the counter stops
How can I proceed ?

Best Regards

**Comment by gtraxx** [comment]
`var timer = new Timer();
        var timeout = setTimeout(startTimer, 3000);

        function startTimer() {
            timer.start({
                startValues: {
                    minutes: 1
                }
            });
            console.log(timer.getTimeValues().toString());
            timer.addEventListener('minutesUpdated', function (e) {
                console.log(timer.getTimeValues().toString());
                test();
            });
        }

        function stopTimer() {
            clearTimeout(timeout);
            timer.stop();
            timer.addEventListener('stopped', function (e) {
                console.log(timer.getTimeValues().toString());
                console.log('stop timer');
            });
            //var timeout = setTimeout(startTimer, 3000);
        }`

**Comment by albert-gonzalez** [comment]
Hi!

I created a fiddle doing something like that you want to do:

https://jsfiddle.net/xpvt214o/303935/

When you click the button, the timer starts in second 55. 5 seconds later, when the minute counter is updated, the listener is executed and stops the timer because the test function returns true.

I hope it helps you.

Best regards!
