### ISSUE TITLE
No exception thrown when typo in configuration constants

### ISSUE THREAD

**Issue by bugallos** [albert-gonzalez/easytimer.js#64]
Hi,
First of all I'd like to say that I enjoy using that library. Good job!
I'm backend developer, coding JavaScripts ocasionally. Though I don't know if I'm correct.

I put typo in "secondTenths" word. I wrote it : "secondTe**h**nths".
Like in code below: 

`timer.start({startValues: {secondTehnths: some_val }})`

It would be a nice feature, If exception has been thrown in console, so users does not have to search for bugs as long as I did.
I know, It was my fault writing typo but It is always nice to have some sort of validation.
Greetings!

**Comment by albert-gonzalez** [comment]
Hi bugallos!

You are right, it would be nice to add this feature. I will try to add it asap.

Best regards!

**Comment by albert-gonzalez** [comment]
Hi!

I have just published the version 3.1.0. I added some validation in startValues, target and precision. I did not add more validations because it could make the parameters configuration very rigid, and it could break existing code using previous versions too. I think that these are the most sensitive parameters to validate.

If you want a better validation, you can use Typescript. With TS you can avoid all these mistakes like the one happened to you.

I close the issue, if you need further help, please comment :).

Best regards!
