### ISSUE TITLE
Timer value changes when the system time is changed

### ISSUE THREAD

**Issue by chandrakanthi07** [albert-gonzalez/easytimer.js#77]
I noticed that the timer goes forward if the system time is forwarded.
Is it possible to avoid this ?

**Comment by albert-gonzalez** [comment]
Hi,

no, I am sorry, the timer uses DateTime to guarantee precision.

**Comment by albert-gonzalez** [comment]
Hi again!

I have been trying to fix this issue using other methods instead of Date, but I didn't find any solution. If you want to know if the user changed the time, a solution is to save in your server when the user started the timer, and when the user stops the timer you can calculate exactly how much time has passed.

Sorry for the inconvenience.

Best regards!
