### ISSUE TITLE
Countdown Timer

### ISSUE THREAD

**Issue by PurpleCapacitor** [albert-gonzalez/easytimer.js#83]
When you enter a value more than 24h, it converts it. I'm not sure if it's a bug or it's intended function. Let me explain:

When you enter 24 hours, countdown will start at 00:00:00 then follow with 23:59:59 and so on. When you enter 25 hours, countdown starts at 01:00:00 and will only countdown 1 hour, not 25 hours. Same will happen with minutes and/or seconds if you go over the 24 hour mark.

**Comment by albert-gonzalez** [comment]
Hi!

You can pass the units that you want to show to the toString function. If you another format that the given by toString function, you can get the values from getTimeValues directly a format them as you wish. You can use also getTotalTimeValues if you need that the counter shows 25 hours instead of 1 day and 24 hours.

I have made this little example to show you how you can use toString with a time greater than 24 hours: https://runkit.com/albert-gonzalez/5d6e9fde790baf001a4795c7

Best regards!

**Comment by PurpleCapacitor** [comment]
Alright then, thanks for the assistance. :)
